[flavor]
use = "catppuccin-mocha"

[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "yellow" },

    # Media
    { mime = "{audio,video}/*", fg = "magenta" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "cyan" },

    # Empty files
    # { mime = "inode/empty", fg = "red" },

    #############################################
    # Add the 2 lines below
    # Hidden files
    { name = "*", is = "hidden", bg = "cyan" },
    #############################################

    # Special files
    { name = "*", is = "orphan", bg = "red" },
    { name = "*", is = "exec", fg = "green" },

    # Dummy files
    { name = "*", is = "dummy", bg = "red" },
    { name = "*/", is = "dummy", bg = "red" },

    # Fallback
    # { name = "*", fg = "white" },
    { name = "*/", fg = "blue" },
]
