[mgr]
show_hidden = true
show_symlink = true
ratio = [2, 2, 3]
#sort_by = "natural"
sort_by = "alphabetical"
sort_translit = true
sort_sensitive = false
sort_dir_first = true
scrolloff = 2

# git plugin
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"
[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
